name: 'Build and Test'
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build-and-test:
    name: 'Build and test'
    runs-on: 'macos-13'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'
      - name: 'Select Xcode'
        run: sudo xcode-select -s '/Applications/Xcode.app'
      - name: 'Build'
        run: |
          xcodebuild build \
          -project Wallhavend.xcodeproj \
          -scheme Wallhavend \
          -configuration Debug \
          -destination 'platform=macOS' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO
      - name: 'Run tests'
        run: |
          xcodebuild test \
          -project Wallhavend.xcodeproj \
          -scheme Wallhavend \
          -configuration Debug \
          -destination 'platform=macOS' \
          -testPlan Wallhavend \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO
