name: 'Build and Test'
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build-and-test:
    name: 'Test'
    runs-on: 'macos-13'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'
      - name: 'Select Xcode'
        run: sudo xcode-select -s '/Applications/Xcode.app'
      - name: 'Build and Test'
        run: |
          xcodebuild \
          -project Wallhavend.xcodeproj \
          -scheme Wallhavend
          -target WallhavendTests \
          -target WallhavendUITests \
          -configuration Debug \
          -destination 'platform=macOS' \
          test \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO
