name: 'Build and Test'
on:
  push:
    branches:
      - 'main'
jobs:
  build-and-test:
    name: 'Build and test'
    strategy:
      matrix:
        swift: ['5.7']
    runs-on: 'macos-latest'
    steps:
      - uses: 'swift-actions/setup-swift@65540b95f51493d65f5e59e97dcef9629ddf11bf'
        with:
          swift-version: "${{ matrix.swift }}"
      - name: 'Checkout'
        uses: 'actions/checkout@v4'
      - name: 'Initialize package'
        run: 'swift package init --type executable'
      - name: 'Build'
        run: 'swift build'
      - name: 'Run tests'
        run: 'swift test'
