name: 'Build and Test'
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build-and-test:
    name: 'Build and test'
    strategy:
      matrix:
        swift-version: ['5.7']
    runs-on: 'macos-13'
    steps:
      - name: 'Setup Swift'
        uses: 'swift-actions/setup-swift@65540b95f51493d65f5e59e97dcef9629ddf11bf'
        with:
          swift-version: "${{ matrix.swift-version }}"
      - name: 'Checkout'
        uses: 'actions/checkout@v4'
      - name: 'Initialize a new package'
        run: 'swift package init --type executable'
      - name: 'Build'
        run: 'swift build'
      - name: 'Run tests'
        run: 'swift test'
